# Generated by Django 3.0.3 on 2020-12-27 13:31

import dbmsA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsA', '0002_businfo_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='price',
            field=models.IntegerField(),
        ),
    ]
