# Generated by Django 3.0.3 on 2020-12-27 13:32

import dbmsA.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsA', '0003_auto_20201227_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='businfo',
            name='rate',
            field=models.FloatField(default=5.0, null=True),
        ),
    ]
