# Generated by Django 3.0.3 on 2020-12-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsA', '0004_auto_20201227_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='experience',
            field=models.TextField(null=True),
        ),
    ]
