# Generated by Django 3.0.3 on 2020-12-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmsA', '0006_auto_20201228_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businfo',
            name='bustype',
            field=models.CharField(choices=[('AC', 'AC'), ('NON AC', 'NON AC')], max_length=10),
        ),
    ]
